"""add_user_tags_and_expense_tags_tables

Revision ID: cd67a086746f
Revises: ba466caabfa1
Create Date: 2025-12-15 00:27:25.540285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd67a086746f'
down_revision: Union[str, Sequence[str], None] = 'ba466caabfa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create user_tags table for standalone user tags
    op.create_table('user_tags',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_tags_id'), 'user_tags', ['id'], unique=False)
    op.create_index(op.f('ix_user_tags_name'), 'user_tags', ['name'], unique=False)

    # Create expense_tags junction table for many-to-many relationship
    op.create_table('expense_tags',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('expense_id', sa.Integer(), nullable=False),
        sa.Column('user_tag_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_tag_id'], ['user_tags.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_tags_id'), 'expense_tags', ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop expense_tags table
    op.drop_index(op.f('ix_expense_tags_id'), table_name='expense_tags')
    op.drop_table('expense_tags')

    # Drop user_tags table
    op.drop_index(op.f('ix_user_tags_name'), table_name='user_tags')
    op.drop_index(op.f('ix_user_tags_id'), table_name='user_tags')
    op.drop_table('user_tags')

    # ### end Alembic commands ###
